// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "GPL 3.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/torrents": {
            "post": {
                "description": "Allow to list, add, remove torrents on server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Handle torrents informations",
                "parameters": [
                    {
                        "description": "Torrent request. Available params for action: add, list, rem.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/torr.torrReqJS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/stream/{hash}/{id}": {
            "get": {
                "description": "Stream a file from a torrent.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Stream a torrent file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File index in torrent",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Torrent data"
                    }
                }
            }
        }
    },
    "definitions": {
        "torr.torrReqJS": {
            "type": "object",
            "properties": {
                "action": { "type": "string" },
                "hash": { "type": "string" },
                "link": { "type": "string" },
                "title": { "type": "string" },
                "poster": { "type": "string" },
                "category": { "type": "string" },
                "data": { "type": "string" },
                "save_to_db": { "type": "boolean" }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "Matrix.135",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Minimal Torrserver Daemon API",
	Description:      "A minimal torrent streaming server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}